// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'dailypaper-analyze-collection'
  | 'dailypaper-analyze-selected'
  | 'dailypaper-score-feed'
  | 'dailypaper-score-selected'
  | 'menuitem-filemenulabel'
  | 'menuitem-label'
  | 'menuitem-submenulabel'
  | 'menupopup-label'
  | 'pref-help'
  | 'pref-title'
  | 'prefs-table-detail'
  | 'prefs-table-title'
  | 'prefs-title'
  | 'startup-begin'
  | 'startup-finish'
  | 'tabpanel-lib-tab-label'
  | 'tabpanel-reader-tab-label';
