// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "apiKey": string;
      "apiBase": string;
      "apiModel": string;
      "collection": string;
      "autoScore": boolean;
      "autoScoreHour": number;
      "autoScoreMinute": number;
      "scoreThreshold": number;
      "scoreConcurrency": number;
      "autoClassify": boolean;
      "categorySynonyms": string;
      "researchTopics": string;
      "scorePromptBase": string;
      "classifyPromptBase": string;
      "analyzePromptFulltext": string;
      "analyzePromptAbstract": string;
    };
  }
}
